---
- name: Instalo el script de install.sh
  template:
    src: install-nexus.sh.j2
    dest: "/home/ubuntu/navent/bin/install.sh"
    mode: 0777
    owner: ubuntu

- name: Ejecuto el script de install.sh
  shell: "sh /home/ubuntu/navent/bin/install.sh"

- name: Instalo la aplicación en supervisor
  become: yes
  template:
    src: app-supervisor.conf.j2
    dest: "/home/ubuntu/navent/supervisor/conf.d/{{app_name}}.conf"

- name: Instalo el script startup.sh
  template:
    src: startup.sh.j2
    dest: "/home/ubuntu/navent/bin/startup.sh"
    mode: 0777
    owner: ubuntu

- name: Copio el script de check web up
  template:
     src: checkWebServerUp.sh.j2
     dest: /home/ubuntu/navent/bin/checkWebServerUp.sh
     mode: 0777
     owner: ubuntu

- name: Instalo el script shutdown.sh 
  template:
    src: shutdown.sh.j2
    dest: "/home/ubuntu/navent/bin/shutdown.sh"
    mode: 0777
    owner: ubuntu

- name: Reload supervisor
  become: yes
  service: name=supervisor state=reloaded
