---
- name: Copio el context File
  become: yes
  template:
    src: tomcat/ROOT.xml.j2
    dest: "{{ tomcat_root_conf }}/ROOT.xml"

- name: Clean artifact path
  become: yes
  command: "rm -rf {{ tomcat_root_home }}/ROOT"

- name: Instalo el script de install.sh
  template:
    src: install-nexus.sh.j2
    dest: "/home/ubuntu/{{navent_folder}}/bin/install.sh"
    mode: 0777
    owner: "ubuntu"

- name: Ejecuto el script de install.sh
  shell: "sh /home/ubuntu/{{navent_folder}}/bin/install.sh {{maven_version}}"

- name: Instalo el script startup.sh
  template:
    src: startup-tomcat.sh.j2
    dest: "/home/ubuntu/{{navent_folder}}/bin/startup.sh"
    mode: 0777
    owner: "ubuntu"

- name: Copio el script de check web up
  template:
     src: checkWebServerUp.sh.j2
     dest: /home/ubuntu/{{navent_folder}}/bin/checkWebServerUp.sh
     mode: 0777
     owner: "ubuntu"

- name: Instalo el script shutdown.sh 
  template:
    src: shutdown-tomcat.sh.j2
    dest: "/home/ubuntu/{{navent_folder}}/bin/shutdown.sh"
    mode: 0777
    owner: "ubuntu"

- name: Paro el tomcat
  become: yes
  shell: "sh /home/ubuntu/{{navent_folder}}/bin/shutdown.sh"

- name: Levanto el tomcat
  become: yes
  shell: "sh /home/ubuntu/{{navent_folder}}/bin/startup.sh"
