---
- name: Instalo el script de install.sh
  template:
    src: tomcat/ROOT.xml.j2
    dest: "{{ tomcat_home }}/ROOT"
    owner: tomcat

- name: Instalo el script de install.sh
  template:.xml
    src: install-nexus.sh.j2
    dest: "/home/ubuntu/navent/bin/install.sh"
    mode: 0777
    owner: tomcat

- name: Ejecuto el script de install.sh
  shell: "sh /home/ubuntu/navent/bin/install.sh {{maven_version}}"

- name: Instalo el script startup.sh
  template:
    src: startup-tomcat.sh.j2
    dest: "/home/ubuntu/navent/bin/startup.sh"
    mode: 0777
    owner: tomcat

- name: Copio el script de check web up
  template:
     src: checkWebServerUp.sh.j2
     dest: /home/ubuntu/navent/bin/checkWebServerUp.sh
     mode: 0777
     owner: ubuntu

- name: Instalo el script shutdown.sh 
  template:
    src: shutdown-tomcat.sh.j2
    dest: "/home/ubuntu/navent/bin/shutdown.sh"
    mode: 0777
    owner: ubuntu

- name: Paro el tomcat
  become_user: tomcat
  shell: "sh /home/ubuntu/navent/bin/shutdown.sh"

- name: Levanto el tomcat
  become_user: tomcat
  shell: "sh /home/ubuntu/navent/bin/startup.sh"