---
# tasks file for install-app

- include: install-supervisor-app.yml 

- hosts: web
  become: yes
  tasks:
     - name: Copio el script de check web up
       template:
          src: checkWebServerUp.sh.j2
          dest: /home/ubuntu/navent/bin/checkWebServerUp.sh
          mode: 0777
          owner: ubuntu
